Repository Ebazhanov/linkedin-skill-assessments-quizzes, pull requests merged in 2021-10, with the labels that each got.

#2312 Add new JSON question
  json/json-quiz.md
Labels: hacktoberfest-accepted

#2318 Cybersecurity Assessment Linkedin Quizz
  cybersecurity-assessment/cybersecurity-assessment.md
  git/git-quiz.md
Labels: merge conflicts

#2321 Added examples and reference links
  README.md
  python/python-quiz.md
Labels: hacktoberfest-accepted, merge conflicts

#2328 Angular Questions Answered
  angular/angular-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2330 Added new Q&A to Linux Assessment
  linux/linux-assesment.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2331 Update: Added 2 questions to Google Ads
  google-ads/google-analytics-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2332 Update: Added 1 question, correct 1 question
  sharepoint/sharepoint-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2335 Update: Added 2 questions to Adobe Indesign
  adobe-in-design/adobe-in-design-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2336 Update: Added correct answers for 2 questions in Eclipse
  eclipse/eclipse-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2339 Updated: C (Programming Language), Q35 discussion (Issue resolved)
  c-(programming-language)/c-quiz.md
  python/python-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2340 added 2 questions in CSS
  css/css-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2342 Update php-quiz.md
  php/php-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2343 Added answer to image question.
  adobe-xd/adobe-xd-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2344 Fixed letter case.
  README.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2345 Update swift-quiz.md
  swift/swift-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2350 New mysql questions
  mysql/images/mysql_q88.png
  mysql/mysql-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2351 <#2311> Adding new microsoft-word question with valid answer
  microsoft-word/microsoft-word-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2353 HTML update
  html/html-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2573 Add a new Django assessment missing question.
  django/django-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2574 Update python-quiz.md
  python/python-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2576 Add more questions to the Go skill quiz with their corresponding answers
  go/go-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2577 Fixed markdown typo of Q4
  css/css-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2578 Fixed format of Q45 and Q58
  php/php-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2579 Fixed the format of Q66 in C++
  c++/c++quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2581 New javascript question
  javascript/javascript-quiz.md
  react/reactjs-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2582 Updated the reference for Q7 and Q15
  c++/c++quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2583 Added Reference for Q70, Q9, Q17
  c++/c++quiz.md
  c-(programming-language)/c-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021

#2585 Added Reference For Q13 and Q16 in C programming.
  c-(programming-language)/c-quiz.md
Labels: hacktoberfest-accepted, Hacktober-Fest 2021
